class Rama{
	public static void main(String[] args){
		System.out.println("OHM VIGNESWARAYANAMAHA");
		System.out.println("OHM SRI LAKSHMI PADMAVATHI SAMETHA VENKATESWARAYANAMAHA");
		System.out.println("OHM NAMAH SHIVAYA");
		System.out.println("OHM MAHA GANAPATAYENAMAHA");
		System.out.println("SRI GURUBHYONNAMAHA");
		System.out.println("OHM NAMO NARAYANAYA");
		System.out.println("OHM SRI BHADRAVATHI SAMETHA BHAVA NARAYANAYA");
		System.out.println("OHM SRI SAINADHAYANAMAHA");
		System.out.println("GURUDEVA NAMOSTHUTE");
	}	
		
}
/*
F:\BHAVAJAVA>java Rama.java
OHM VIGNESWARAYANAMAHA
OHM SRI LAKSHMI PADMAVATHI SAMETHA VENKATESWARAYANAMAHA
OHM NAMAH SHIVAYA
OHM MAHA GANAPATAYENAMAHA
SRI GURUBHYONNAMAHA
OHM NAMO NARAYANAYA
OHM SRI BHADRAVAHI SAMETHA BHAVA NARAYANAYA
OHM SRI SAINADHAYANAMAHA
GURUDEVA NAMOSTHUTE
*/
