class Rama{
	public static void main(String[] args){
		System.out.println("OHM MAHA GANAPATAYENAMAHA");
		System.out.println("SRI GURUBHYONNAMAHA");
		System.out.println("OHM NAMO NARAYANAYA");
		System.out.println("OHM BHADRAVATHI BHAVANARAYANA NAMAHA");
		System.out.println("OHM NAMAH SIVAIAH");
		System.out.println("OHM SRI RAMA CHANDRA PARABRAMHANENAMAHA");
		System.out.println("OHM NAMO VENKATESHAYA");
	}
}	

/*
F:\BHAVAJAVAWIPRO>javac Rama.java

F:\BHAVAJAVAWIPRO>java Rama
OHM MAHA GANAPATAYENAMAHA
SRI GURUBHYONNAMAHA
OHM NAMO NARAYANAYA
OHM BHADRAVATHI BHAVANARAYANA NAMAHA
OHM NAMAH SIVAIAH
OHM SRI RAMA CHANDRA PARABRAMHANENAMAHA
OHM NAMO VENKATESHAYA
*/